apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: developer-conventions
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting conventions"
spec:
  serviceAccountName: cluster-admin-sa
  packageRef:
    refName: developer-conventions.tanzu.vmware.com
    versionSelection:
      constraints: 0.2.0
      prereleases: {}
