apiVersion: v1
kind: Namespace
metadata:
  name: tap-install
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-tap-repository
  namespace: tap-install
spec:
  fetch:
    imgpkgBundle:
      image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages:0.2.0
