apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: scp-toolkit
  namespace: tap-install
spec:
  serviceAccountName: cluster-admin-sa
  packageRef:
    refName: scp-toolkit.tanzu.vmware.com
    versionSelection:
      constraints: 0.3.0
      prereleases: {}
