apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: metadata-store
  namespace: tap-install
spec:
  serviceAccountName: cluster-admin-sa
  packageRef:
    refName: scst-store.tanzu.vmware.com
    versionSelection:
      constraints: 1.0.0-beta.0
      prereleases: {}
  values:
  - secretRef:
      name: metadata-store-values
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: metadata-store-values
#   namespace: tap-install
# stringData:
#   scst-store-values.yaml: |
#     db_password: "CHANGEME!!"
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: metadata-store-values
  namespace: tap-install
spec:
  secretTemplate:
    type: Opaque
    stringData:
      values.yaml: |
        db_password: $(password)
