apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tap-full-alt-cluster-admin-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tap-full-alt-cluster-admin-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tap-full-alt-cluster-admin-role
subjects:
- kind: ServiceAccount
  name: tap-full-alt-cluster-admin-sa
  namespace: tap-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-full-alt-cluster-admin-sa
  namespace: tap-install
