#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tap-full
  namespace: tap-install
spec:
  serviceAccountName: tap-full-alt-cluster-admin-sa
  packageRef:
    refName: tap-full.tanzu.vmware.com
    versionSelection:
      constraints: 0.0.1
  values:
  - secretRef:
      name: tap-full-values
---
apiVersion: v1
kind: Secret
metadata:
  name: tap-full-values
  namespace: tap-install
stringData:
  values.yaml: #@ yaml.encode(data.values)
